### ISSUE TITLE
Problems re entering or joining a new game when leaving an existing game. 

### ISSUE THREAD

**Issue by BrainRayChristensen** [byucs340ta/Fall2018#139]
If you enter a game and then leave a game It causes all sorts of errors if you try to do anything else including:
- having more destination cards than you should when opening the destination card screen( I couldn't find a prcocess to recreate this one, it just happened randomly it seemed)
- the game sometimes crashing
- when you leave the game, the lobby won't update automatically until you click the join game button again.
- an error we like to call disco cards: when you leave a game and join a new one, the face up train car cards switch back and forth between two or more sets of cards, and the players also do the same between the old set of players and the new set.

**Comment by marceloarchiza** [comment]
This bug is actually 4 different bugs.
Bug 1: Still need to be analyzed more. We are not being able to repro right now.
Bug 2: The game is not crashing for us. We are not sure how to repro this bug.
Bug 3: Nice catch. This bug was happening because the poller was not restarting when returning, unless you clicked on join button again. We forgot to finish the game list fragment before entering the game. Doing that fixed this bug. **Bug fixed.**
Bug 4: The poller is not being turned off, this was fixed.

John fixed these bugs, except for bug 1 and 2, since they are super inconsistent and we don't have enough info to repro them.
